{
	"version": 1604774992,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/backgroundload.png",
		"images/bar.png",
		"images/chargement.png",
		"images/btn_new_game-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/buton-sheet0.png",
		"images/buton-sheet1.png",
		"images/door1-sheet0.png",
		"images/feu_follet-sheet0.png",
		"images/key1-sheet0.png",
		"images/levier-sheet0.png",
		"images/levier-sheet1.png",
		"images/lior-sheet0.png",
		"images/lior-sheet1.png",
		"images/lior-sheet2.png",
		"images/ronces-sheet0.png",
		"images/wall-sheet0.png",
		"images/door2-sheet0.png",
		"images/door5-sheet0.png",
		"images/camera-sheet0.png",
		"images/particles2.png",
		"images/sprite4-sheet0.png",
		"images/active_zone-sheet0.png",
		"images/danger_zone-sheet0.png",
		"images/net_lvl-sheet0.png",
		"images/interface_btn_parameter-sheet0.png",
		"images/interface_door-sheet0.png",
		"images/interface_key-sheet0.png",
		"images/interface_bar-sheet0.png",
		"images/aqua-sheet0.png",
		"images/end_game-sheet0.png",
		"images/sprite5-sheet0.png",
		"media/muscchim-accroche-reve-id-0040-ls_efo6ocwj (online-audio-converter.com).ogg",
		"media/mechclik-interrupteur-id-0026-ls_6kma4hx0 (online-audio-converter.com).ogg",
		"media/doorswng-grincements-id-0605-ls_52hkjcsy (online-audio-converter.com).ogg",
		"media/clockmech-remontoir-1-id-1674-ls_egdftr4w (online-audio-converter.com).ogg",
		"media/classic_hurt(2) (online-audio-converter.com).ogg",
		"media/objkey-serrure-et-grosse-clef-id-0378-ls_9ng4cx6o (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}